### ISSUE TITLE
CT: passed-in thumbNode must have the correct tandem

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#115]
```
molecule-polarity : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618239924819%22%2C%22timestamp%22%3A1618243368563%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 9:05:24 AM

----------------------------------

molecule-polarity : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/phet-io-wrappers/mirror-inputs/?sim=molecule-polarity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618239924819%22%2C%22timestamp%22%3A1618244970182%7D
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 9:05:24 AM

----------------------------------

molecule-polarity : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/studio/?sim=molecule-polarity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618239924819%22%2C%22timestamp%22%3A1618245983524%7D
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 9:05:24 AM

----------------------------------

molecule-polarity : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-polarity&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: molecule-polarity: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25

Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNodeError: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 9:05:24 AM

----------------------------------

molecule-polarity : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-polarity
3 out of 4 tests passed. 1 failed.
SimTests: molecule-polarity: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25

Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNodeError: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumb, actual: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.thumbNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/sun/js/HSlider.js:27:5)
at new ElectronegativitySlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativitySlider.js:73:5)
at new ElectronegativityPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/common/view/ElectronegativityPanel.js:62:20)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:55:41)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618239924819/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 9:05:24 AM
```

**Comment by pixelzoom** [comment]
This is a general issue that was reported in https://github.com/phetsims/sun/issues/694.  I'll keep this issue open to remind me that it impacts this sim.

**Comment by pixelzoom** [comment]
The pieces of this related to phetsims/sun#694 have been fixed, so closing.
