### ISSUE TITLE
Assertion failed: y should be a finite number

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#167]
From adding fuzzing features in https://github.com/phetsims/phet-io/issues/2003.

```
molecule-polarity : phet-io-fuzz : unbuilt : assertSlow
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1734037474418/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1734037474418%22%2C%22timestamp%22%3A1734039205986%7D&eall&brand=phet-io&phetioStandalone&fuzz
ERROR: QUERY: eall&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: y should be a finite number
STACK: Error: Assertion failed: y should be a finite number
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1734037474418/assert/js/assert.js:45:21)
    at assert (../../../../../../scenery/js/nodes/Node.ts:2458:16)
    at translate (../../../../../../scenery/js/nodes/Node.ts:3235:11)
    at setBottom (../../../../../../scenery/js/nodes/Node.ts:3245:9)
    at  (../../../../../../../molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.ts:117:31)
    at callback (../../../../../axon/js/Multilink.ts:111:10)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/TinyStaticProperty.ts:56:9)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1570:30)
    at validateBounds (../../../../../../scenery/js/nodes/Node.ts:1682:18)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1668:17)
    at validateWatchedBounds (../../../../../../scenery/js/display/Display.ts:568:19)
    at updateDisplay (../../../../../joist/js/Sim.ts:476:21)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../joist/js/Sim.ts:1079:30)

```

**Comment by zepumph** [comment]
This seems like a good case to handle outside of common code. If the electronegativityPanels are hidden (the container or all children), then the bondCharacterPanel seems like it should float down to give more play area spacing. @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
I agree that this should be handled in sim code. But https://github.com/phetsims/molecule-polarity/commit/95ddda3d1f69c75203ac09a5fc3120e9c6daed7d is not what we want to have happen.  These panels should always be in the same position, regardless of visibilty.  If electronegativityPanels is invisible, we definitely do not want bondCharacterPanel to move to the bottom of the ScreenView, it should always be near closer to the molecules.

**Comment by pixelzoom** [comment]
Resolved in https://github.com/phetsims/molecule-polarity/commit/5ef4d4b7dc8b6989f7e06c90affc797b970b3ac6 by adding a VBox with `excludeInvisibleChildrenFromBounds: false`.  Closing.
