### ISSUE TITLE
Error: Assertion failed: homeScreenIcon has invalid aspect ratio: ...

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-polarity#23]
Run the sim with `?stringTest=xss` to get this error.

```
Uncaught Error: Assertion failed: homeScreenIcon has invalid aspect ratio: 34.60004660271448
Error: Assertion failed: homeScreenIcon has invalid aspect ratio: 34.60004660271448
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/assert/js/assert.js:21:13)
    at validateIconSize (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/Screen.js?bust=1491333041288:119:15)
    at TwoAtomsScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/Screen.js?bust=1491333041288:75:5)
    at new TwoAtomsScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/molecule-polarity/js/twoatoms/TwoAtomsScreen.js?bust=1491333041288:42:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/molecule-polarity/js/molecule-polarity-main.js?bust=1491333041288:35:7
    at window.phetLaunchSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333041288:50:11)
    at doneLoadingImages (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333041288:60:18)
    at Object.launch (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333041288:114:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/molecule-polarity/js/molecule-polarity-main.js?bust=1491333041288:32:15
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/sherpa/lib/require-2.1.11.js:1650:25)
Approximately 4/4/2017, 12:52:10 PM
```

**Comment by pixelzoom** [comment]
Fixed in master. @phet-steele please verify.

**Comment by phet-steele** [comment]
Looks fixed, thanks @pixelzoom!
