### ISSUE TITLE
complete the "Real Molecules" screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#32]
Because of the time involved in implementing a 3D molecule viewer (#15), the decision was made to publish Molecule Polarity without the Real Molecules screen (#27). 

When the Real Molecules screen is added in a future version, here's what needs to be done:

- [ ] Implement a 3D molecule viewer, #15
- [ ] Address TODO issues in the code that reference issue #15
- [ ] Code review for any new code that is required to complete the screen  
- [ ] Add description of the 3D model to model.md
- [ ] Add description of the 3D implementation to implementation-notes.md

**Comment by oliver-phet** [comment]
From phethelp:
> I appreciate all the work that has been done to maintain PhET invaluable simulations through converting them to HTML5 format. Without taking too much of your time, I'm writing to request that someone work to adapt the "Real Molecules" function of the Molecule Polarity simulation to HTML5. Its so important for students to see the effect of polarity on larger, organic molecules with multiple dipoles to understand the concepts of solubility.

**Comment by pixelzoom** [comment]
Status for 1/6/2022 quarterly-planning meeting:

The status of this is unchanged since the last meeting:
* Basic 3D common-code exists, but nothing specifically related to molecules or this sim.
* We need a meeting to decide who is doing what, and how to move forward.
* The ball is in @kathy-phet's court.

**Comment by samreid** [comment]
More strict assertions introduced in https://github.com/phetsims/sun/issues/920 make a workaround here more difficult. The simulation fails CTQ with:

```
Error in molecule-polarity: Error: Assertion failed: Error: Assertion failed: Property should be instrumented if AquaRadioButtonGroup is instrumented
    at window.assertions.assertFunction (http://localhost:40339/assert/js/assert.js:45:21)
    at http://localhost:40339/chipper/dist/js/joist/js/simLauncher.js:24:31
/data/share/phet/continuous-testing/ct-quick/chipper/js/phet-io/generatePhetioMacroAPI.ts:110
        throw new Error( workerResult.reason );
```

To resolve CTQ for now, I will remove the workaround in https://github.com/phetsims/molecule-polarity/blob/f37631042adcb39796ba6765ca3e5737a49df02d/js/common/model/MPPreferences.ts#L25-L37 but this issue will likely need attention before next publication.

**Comment by pixelzoom** [comment]
@samreid I have concerns about https://github.com/phetsims/molecule-polarity/commit/e04b6bda74c74352fb0c39da66fad3f46dce8f15 and https://github.com/phetsims/phet-io-sim-specific/commit/762977427724d351a5d9900f8f241c73bffa5a8e.  I don't think we want to be adding PhET-iO elements related to the Real Molecules screen, as it appears you've done for `surfaceColorProperty`.  Until then, the tandem for `surfaceColorProperty` should be `Tandem.OPT_OUT.createTandem( 'surfaceColorProperty' )`.

**Comment by pixelzoom** [comment]
Here's a patch for what I think is a preferrable way to address the new constraints introduced for AquaRadioButtonGroup in  https://github.com/phetsims/sun/issues/920.  It does change the published API in that it uninstruments `preferencesPanels.simulationPreferencesPanel.simPreferences.surfaceColorControl` -- which arguably should not have been instrumented in the published version, because it's only relevant for the Real Molecules screen.

@samreid do you see any problem with this?

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] revert to "Spectrometer" for accordion box title
---
Index: js/common/model/MPPreferences.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/MPPreferences.ts b/js/common/model/MPPreferences.ts
--- a/js/common/model/MPPreferences.ts	(revision c3d2361c28db53cd98edba385e7ce59da17f0c58)
+++ b/js/common/model/MPPreferences.ts	(date 1735618395876)
@@ -27,8 +27,9 @@
     MPQueryParameters.surfaceColor as SurfaceColor, {
       validValues: SurfaceColorValues,
 
-      // TODO: It would be preferable to uninstrument this when running without the Real Molecules screen, which is not yet phet-io instrumented, see https://github.com/phetsims/molecule-polarity/issues/32
-      tandem: Tandem.PREFERENCES.createTandem( 'surfaceColorProperty' ),
+      //TODO When Real Molecules screen is eventually implemented, make this tandem change. See https://github.com/phetsims/molecule-polarity/issues/32
+      // tandem: Tandem.PREFERENCES.createTandem( 'surfaceColorProperty' ),
+      tandem: Tandem.OPT_OUT,
       phetioDocumentation: 'color scheme for the Electrostatic Potential surface in the Real Molecules screen',
       phetioFeatured: true
     } )
Index: js/common/view/MPPreferencesNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MPPreferencesNode.ts b/js/common/view/MPPreferencesNode.ts
--- a/js/common/view/MPPreferencesNode.ts	(revision c3d2361c28db53cd98edba385e7ce59da17f0c58)
+++ b/js/common/view/MPPreferencesNode.ts	(date 1735618395869)
@@ -13,6 +13,7 @@
 import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import { VBox, VBoxOptions } from '../../../../scenery/js/imports.js';
+import Tandem from '../../../../tandem/js/Tandem.js';
 import moleculePolarity from '../../moleculePolarity.js';
 import MPPreferences from '../model/MPPreferences.js';
 import MPQueryParameters from '../MPQueryParameters.js';
@@ -41,7 +42,9 @@
     } );
 
     const surfaceColorControl = new SurfaceColorControl( MPPreferences.surfaceColorProperty, {
-      tandem: options.tandem.createTandem( 'surfaceColorControl' )
+      //TODO When Real Molecules screen is eventually implemented, make this tandem change. See https://github.com/phetsims/molecule-polarity/issues/32
+      // tandem: options.tandem.createTandem( 'surfaceColorControl' )
+      tandem: Tandem.OPT_OUT
     } );
 
     //TODO https://github.com/phetsims/molecule-polarity/issues/32
```

</details>

**Comment by samreid** [comment]
Yes, that seems sensible to me. Will we need to add a corresponding `DeleteUninstrumentedPhetioElement` in the migration processors?

**Comment by pixelzoom** [comment]
Yes, we'll need a `DeleteUninstrumentedPhetioElement` for `surfaceColorControl`.

**Comment by samreid** [comment]
It does seem we need a migration processor after all, not due to `surfaceColorControl` itself but to its children. I'll commit momentarily.

**Comment by pixelzoom** [comment]
👍🏻 Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by pixelzoom** [comment]
Oops, I should not have closed this issue -- which is about completing the Real Molecules screen, and not about addressing changes related to https://github.com/phetsims/sun/issues/920.  In retrospect, it would have been preferrable to create a new issue to address those changes.

**Comment by pixelzoom** [comment]
In the above commits, I was asked to remove the `?realMolecules` query parameter.  And in order to do that, I also had to flesh out the PhET-iO instrumentation for the "Real Molecules" screen. 

Those changes prevent this sim from being published until the "Real Molecules" screen is completed.  So I've added the "blocks-sim-publication" label to this issue.
