### ISSUE TITLE
CT invalid molecule

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#86]
```
molecule-polarity : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (molecule-polarity, brands: phet)
Building brand: phet
>> Webpack build complete: 4144ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: repo balancing-chemical-equations missing from package.json's phetLibs for balancing-chemical-equations/js/balancingChemicalEquations.js
at /data/share/phet/continuous-testing/ct-snapshots/1614723829308/chipper/js/grunt/buildRunnable.js:125:5
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1614723829308/chipper/js/grunt/buildRunnable.js:123:29)
at /data/share/phet/continuous-testing/ct-snapshots/1614723829308/chipper/js/grunt/Gruntfile.js:254:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1614723829308/chipper/js/grunt/Gruntfile.js:73:7)

Full Error details:
AssertionError [ERR_ASSERTION]: repo balancing-chemical-equations missing from package.json's phetLibs for balancing-chemical-equations/js/balancingChemicalEquations.js
Snapshot from 3/2/2021, 3:23:49 PM

----------------------------------

molecule-polarity : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614723829308%22%2C%22timestamp%22%3A1614726294851%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid molecule
Error: Assertion failed: invalid molecule
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/assert/js/assert.js:25:13)
at new MoleculeAngleDragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/common/view/MoleculeAngleDragListener.js:25:15)
at new SurfaceNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/SurfaceNode.js:74:28)
at new ElectrostaticPotentialNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/ElectrostaticPotentialNode.js:27:5)
at new DiatomicMoleculeNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/DiatomicMoleculeNode.js:63:40)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:53:26)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:923:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:931:25
id: Bayes Chrome
Snapshot from 3/2/2021, 3:23:49 PM

----------------------------------

molecule-polarity : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614723829308%22%2C%22timestamp%22%3A1614725432726%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: invalid molecule
Error: Assertion failed: invalid molecule
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/assert/js/assert.js:25:13)
at new MoleculeAngleDragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/common/view/MoleculeAngleDragListener.js:25:15)
at new SurfaceNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/SurfaceNode.js:74:28)
at new ElectrostaticPotentialNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/ElectrostaticPotentialNode.js:27:5)
at new DiatomicMoleculeNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/DiatomicMoleculeNode.js:63:40)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:53:26)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:923:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:931:25
id: Bayes Chrome
Snapshot from 3/2/2021, 3:23:49 PM

----------------------------------

molecule-polarity : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614723829308%22%2C%22timestamp%22%3A1614725846517%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: invalid molecule
Error: Assertion failed: invalid molecule
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/assert/js/assert.js:25:13)
at new MoleculeAngleDragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/common/view/MoleculeAngleDragListener.js:25:15)
at new SurfaceNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/SurfaceNode.js:74:28)
at new ElectrostaticPotentialNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/ElectrostaticPotentialNode.js:27:5)
at new DiatomicMoleculeNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/DiatomicMoleculeNode.js:63:40)
at new TwoAtomsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/view/TwoAtomsScreenView.js:53:26)
at TwoAtomsScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/molecule-polarity/js/twoatoms/TwoAtomsScreen.js:42:16)
at TwoAtomsScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:923:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614723829308/joist/js/Sim.js:931:25
id: Bayes Chrome
Snapshot from 3/2/2021, 3:23:49 PM
```

**Comment by pixelzoom** [comment]
Yeah, sorry that snuck in.  This sim is undergoing a "PhET-iO instrumentation sprint", so there are going to be problems for a little bit. 

This one was fixed within the past hour. Closing.
