### ISSUE TITLE
CT: phetioID already registered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#96]
```
molecule-polarity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/phet-io-wrappers/state/?sim=molecule-polarity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1615352942127%22%2C%22timestamp%22%3A1615354856949%7D
Uncaught Error: Assertion failed: phetioID already registered: moleculePolarity.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.dipoleDirectionControl.titleText
Error: Assertion failed: phetioID already registered: moleculePolarity.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.dipoleDirectionControl.titleText
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/phet-io/js/phetioEngine.js:465:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/phet-io/js/phetioEngine.js:1042:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/tandem/js/Tandem.js:166:38)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/tandem/js/PhetioObject.js:268:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/scenery/js/nodes/Node.js:6629:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/scenery/js/nodes/Text.js:216:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/scenery/js/nodes/Node.js:6599:10)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/scenery/js/nodes/Text.js:94:10)
at new DipoleDirectionControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615352942127/molecule-polarity/js/common/view/DipoleDirectionControl.js:37:23)
id: Bayes Chrome
Snapshot from 3/9/2021, 10:09:02 PM
```

**Comment by pixelzoom** [comment]
To reproduce manually:

1. Run the sim in the State wrapper, `.../phet-io-wrappers/state/?sim=molecule-polarity&phetioDebug&phetioValidation=true`
2. In the upstream sim, select PhetMenu > Options to open the Options dialog
3. Close the Options dialog by clicking on the close (X) button.  This will trigger the error.

The console reads:

> Assertion failed: phetioID already registered: moleculePolarity.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.dipoleDirectionControl.titleText
phetioAPIValidation.js:227 error data: {phetioID: "moleculePolarity.general.view.navigationBar.phetBu…phetMenu.optionsDialogCapsule.optionsDialog.title", ruleInViolation: "1. After startup, only dynamic instances prescribed by the baseline file can be registered."}
assert.js:21 Assertion failed: PhET-iO API error:
moleculePolarity.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.title:  1. After startup, only dynamic instances prescribed by the baseline file can be registered.

MPOptionsNode is the content for my Options dialog, it implements `dispose`, and it disposes of subcomponents that have registered tandems.  Options content is provided to Sim in main.js like this:

```js
  // Creates content for the Options dialog
  createOptionsDialogContent: tandem => new MPOptionsNode( {
    tandem: tandem
  } ),
```

@samreid @zepumph please advise on how to proceed.

**Comment by pixelzoom** [comment]
I figured this out.  MPOptions was disposing of its subcomponents.  But those subcompoents had subcomponents that weren't being cleaned up -- specifically radio button Text labels.  

Fixed in the above commit. Closing.
